//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int Id { get; set; }
        public string Token1 { get; set; }
        public int UserId { get; set; }
        public System.DateTime Expiry { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
